# Generated by Django 5.0.2 on 2024-02-29 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0002_alter_factincidences_id_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factincidences',
            name='incidence_date',
        ),
    ]
