# Generated by Django 5.0.2 on 2024-02-29 12:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0003_remove_factincidences_incidence_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='factincidences',
            name='incidence_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
